<h1>Обзор сервера</h1>
<div class="date">01.01.2007</div>


Обзор сервера</p>
<p>MS SQL Server &#8211; прямой потомок Sybase SQL Server, с которым их до сих пор связывает много общего, в первую очередь язык программирования Transact-SQL (далее T-SQL). Однако, в версии 7.0 Microsoft, по её собственным утверждениям, переписала сервер полностью, так что он больше не содержит кода от Sybase. Главным достоинством MS SQL Server является тесная интеграция с Windows NT и семейством продуктов Back Office &#8211; общая модель защиты, базирующаяся на защите Windows NT, единая консоль администрирования (Microsoft Management Console), единый набор программных интерфейсов для доступа к данным (OLE DB). Текущая версия сервера на момент написания этой книги &#8211; Microsoft SQL Server 2000. Сервер выпускается в следующих редакциях:</p>
<div style="text-align: left; text-indent: 0px; padding: 0px 0px 0px 0px; margin: 0px 0px 0px 24px;"><table border="0" cellpadding="0" cellspacing="0" style="line-height: normal;"><tr><td width="24">&#8226;</td><td>Personal &#8211; версия, работающая на Windows 95 и Windows NT Workstation. Предназначена в основном для отладки при разработке ПО. Поддерживает до 2 процессоров. Реально можно работать (имея загруженным сервер, Query Analyzer и Enterprise Manager) на конфигурации P100/40 Мб под Windows 95.</td></tr></table></div><div style="text-align: left; text-indent: 0px; padding: 0px 0px 0px 0px; margin: 0px 0px 0px 24px;"><table border="0" cellpadding="0" cellspacing="0" style="line-height: normal;"><tr><td width="24">&#8226;</td><td>Standard &#8211; стандартная редакция. Работает под Windows NT Server. Поддерживает до 4 процессоров.</td></tr></table></div><div style="text-align: left; text-indent: 0px; padding: 0px 0px 0px 0px; margin: 0px 0px 0px 24px;"><table border="0" cellpadding="0" cellspacing="0" style="line-height: normal;"><tr><td width="24">&#8226;</td><td>Enterprise &#8211; расширенная редакция. Поддерживает до 32 процессоров, включает в себя некоторые дополнительные возможности.</td></tr></table></div><div style="text-align: left; text-indent: 0px; padding: 0px 0px 0px 0px; margin: 0px 0px 0px 24px;"><table border="0" cellpadding="0" cellspacing="0" style="line-height: normal;"><tr><td width="24">&#8226;</td><td>Developer &#8211; редакция для разработчиков. По функциональности примерно соответствует Enterprise</td></tr></table></div>Кроме этого существует версия SQL Server для Windows CE, предназначенная для портативных компьютеров. Эта версия совместима с остальными версиями сервера по языку и имеет возможности репликации данных с ними.</p>
<p>Таким образом, сервер работает на всей линейке операционных систем Microsoft на процессорах Intel и Alpha.</p>
<p>Также нельзя не упомянуть такой продукт, как Microsoft Data Engine (MSDE) &#8211; версия MS SQL Server без графических средств администрирования и с ограничениями по размеру БД (2Гб) и количеству пользователей (5). Эта версия предназначена для построения встраиваемых систем, которые при необходимости легко могут быть портированы на полнофункциональную редакцию сервера, а также, например, для создания демонстрационных версий продуктов. Администрирование MSDE может производиться при помощи утилиты osql, клиентских утилит от MS SQL Server, либо из MS Access 2000. MSDE поставляется в составе MS Office 2000 Professional и MS Visual Studio.</p>
<p>Из дополнительных возможностей следует отметить:</p>
<div style="text-align: left; text-indent: 0px; padding: 0px 0px 0px 0px; margin: 0px 0px 0px 24px;"><table border="0" cellpadding="0" cellspacing="0" style="line-height: normal;"><tr><td width="24">&#8226;</td><td>OLAP сервер &#8211; средство для создания и представления многомерных кубов данных, использующихся в аналитических системах. На настоящий момент MS SQL является одним из самых дешевых имеющихся на рынке решений подобного рода. OLAP Services входят в стандартную поставку и не требуют дополнительных отчислений.</td></tr></table></div>Полнотекстовый поиск по БД. В сервер включена специальная версия MS Index Server, которая позволяет построить по текстовым (включая BLOB) полям полнотекстовый индекс и расширения SQL, позволяющие строить запросы по этому индексу, например:</p>

<pre>SELECT ProductName</p>
<p>  FROM Products</p>
 WHERE CONTAINS(ProductName, 'spread NEAR Boysenberry')
</pre>

<div style="text-align: left; text-indent: 0px; padding: 0px 0px 0px 0px; margin: 0px 0px 0px 24px;"><table border="0" cellpadding="0" cellspacing="0" style="line-height: normal;"><tr><td width="24">&#8226;</td><td>English Query &#8211; инструмент для формирования запросов на естественном английском языке, например «How many blue Fords were sold in 1996?».</td></tr></table></div><div style="text-align: left; text-indent: 0px; padding: 0px 0px 0px 0px; margin: 0px 0px 0px 24px;"><table border="0" cellpadding="0" cellspacing="0" style="line-height: normal;"><tr><td width="24">В настоящее время существуют решения российских фирм, позволяющие выполнять полнотекстовый поиск на русском языке с учетом словоформ и формировать запросы на русском языке. Ознакомится с ними можно по адресу: http://www.microsoft.com/rus/sql</td></tr></table></div><div style="text-align: left; text-indent: 0px; padding: 0px 0px 0px 0px; margin: 0px 0px 0px 24px;"><table border="0" cellpadding="0" cellspacing="0" style="line-height: normal;"><tr><td width="24">&#8226;</td><td>Data Transformation Services (DTS) &#8211; универсальный инструмент для перемещения данных между гетерогенными источниками. Единственное требование &#8211; наличие ODBC (лучше OLE DB) драйвера. Позволяет создавать сложные сценарии переноса данных. Полезен не только при переносе на MS SQL Server, но и для любой другой БД.</td></tr></table></div><div style="text-align: left; text-indent: 0px; padding: 0px 0px 0px 0px; margin: 0px 0px 0px 24px;"><table border="0" cellpadding="0" cellspacing="0" style="line-height: normal;"><tr><td width="24">&#8226;</td><td>Встроенную в сервер поддержку XML, позволяющую использовать XML-документ в качестве источника данных в запросе и выдавать результаты запроса в виде XML-документа.</td></tr></table></div>Клиентская часть MS SQL Server реализована на платформе Win32. В стандартный комплект поставки входят драйверы, работающие под управлением Windows 95 и Windows NT. Таким образом, в качестве клиента могут выступать все платформы, поддерживаемые Delphi.</p>
<p>Все это делает MS SQL Server привлекательным решением для реализации БД на платформе Windows NT.</p>

