<h1>Duplicate resource error</h1>
<div class="date">01.01.2007</div>


<p>When I try to add a resource to my project's .res file, I get a "Duplicate Resource" error when linking. The resource I have added is a unique resource. How can I successfully add the resource to my project?</p>

<p>The projects resource file is generated by the IDE wizard, and is not intended to be modified. To add additional resources to your project, create a separate resource file with a unique name that does not conflict with either the project or any of&nbsp; the unit names. Then to add the resource file to Delphi, simply add the following line to any unit file in the project:</p>

<p><span style="color: teal;">{$R MyRes.Res}</span></p>

<p>(where MyRes.Res is the name of the resource file).</p>

<p>To add the resource to Borland's C++ Builder, add the resource</p>
<p>from the project manager.</p>

